### ISSUE TITLE
Cp7 - 3  solution

### ISSUE THREAD

**Issue by xgdyp** [datawhalechina/statistical-learning-method-solutions-manual#13]
I think the solution of 7.3 may have some problems.
![image](https://user-images.githubusercontent.com/37795442/142139594-58dbd25d-64f4-4022-a36c-1c9b24416d92.png)
and my final result is 
![image](https://user-images.githubusercontent.com/37795442/142139671-2761adca-4737-4dd4-9395-4aaacf9ac8ef.png)

**Comment by Relph1119** [comment]
感谢，已完成修订
![image](https://user-images.githubusercontent.com/15226799/142148079-77f61a7e-ad2c-414e-a48f-59770192f50d.png)
![image](https://user-images.githubusercontent.com/15226799/142148157-70c7aac5-cc4c-414d-b71f-34544975dd21.png)

**Comment by Relph1119** [comment]
感谢，已完成修订
![image](https://user-images.githubusercontent.com/15226799/142155813-43a43bab-2a57-4762-8bbf-5da6fba5db66.png)
![image](https://user-images.githubusercontent.com/15226799/142155843-eb611df9-1fab-4272-83dc-7d360ebc5d50.png)
