### ISSUE TITLE
习题 4.1，对数似然函数的推导

### ISSUE THREAD

**Issue by clamcy** [datawhalechina/statistical-learning-method-solutions-manual#16]
您好，请问【习题 4.1，对数似然函数】部分的推导：

![Original](https://user-images.githubusercontent.com/44613348/154826121-78e028d3-cb32-4d75-af46-b686b90da71e.png)
是否应该改成：
![Mod](https://user-images.githubusercontent.com/44613348/154826199-8c98820f-f0ad-4037-aef8-b809a7a4e662.png)
虽然这并不影响后续的结论。

$$
\begin{aligned} \displaystyle \log L(p|Y) &= \log C_N^m p^m (1-p)^{N-m} \\
&= \log(C_N^m) + \log(p^m) + \log[ (1-p)^{N-m} ] \\
&= \log(C_N^m) + m\log p + (N-m)\log (1-p)
\end{aligned}
$$

**Comment by Relph1119** [comment]
谢谢，已更新

**Comment by clamcy** [comment]
谢谢！
