### ISSUE TITLE
在线阅读地址打不开

### ISSUE THREAD

**Issue by qiuchenpro** [datawhalechina/statistical-learning-method-solutions-manual#22]
在线阅读地址打不开了，链接点开一直是loading状态。

**Comment by ly-hljxx** [comment]
http://liuyang.223366.INFO

**Comment by Relph1119** [comment]
该问题已经解决，可以正常打卡
![image](https://user-images.githubusercontent.com/15226799/190081828-e403e62a-bd87-4bb1-80f0-59d5ee8a9a3d.png)

**Comment by qiuchenpro** [comment]
> 该问题已经解决，可以正常打卡 ![image](https://user-images.githubusercontent.com/15226799/190081828-e403e62a-bd87-4bb1-80f0-59d5ee8a9a3d.png)

在线阅读中的latex公式不能正常显示，使用Chrome浏览器和Edge浏览器都不能显示公式。

**Comment by Relph1119** [comment]
公式已经可以展示
![image](https://user-images.githubusercontent.com/15226799/190088827-d32dd8d8-6862-4c22-a99d-e532d4bf315d.png)
