### ISSUE TITLE
所有公式都不能正常显示

### ISSUE THREAD

**Issue by zhangfei1947** [datawhalechina/statistical-learning-method-solutions-manual#23]
您好，我使用的是mac设备，safari和Chrome浏览器都不能正常显示公式。
$$ \displaystyle P(Y=c_k) = \frac{\displaystyle \sum......

**Comment by qiuchenpro** [comment]
我的windows用Chrome打开也不能正常显示latex公式.

**Comment by zhangfei1947** [comment]
非常感谢！
