### ISSUE TITLE
Some code questions about problem 3.3 in Chapter 3.

### ISSUE THREAD

**Issue by THUliuxinlong** [datawhalechina/statistical-learning-method-solutions-manual#29]
[Some_code_errors.md](https://github.com/datawhalechina/statistical-learning-method-solutions-manual/files/10093594/Some_code_errors.md)

**Comment by Relph1119** [comment]
不好意思，相关截图看不见，能否在GitHub上面填写内容

**Comment by THUliuxinlong** [comment]
> 不好意思，相关截图看不见，能否在GitHub上面填写内容

[Some_code_errors.pdf](https://github.com/datawhalechina/statistical-learning-method-solutions-manual/files/10119704/Some_code_errors.pdf)

**Comment by Relph1119** [comment]
已修复，谢谢反馈
