### ISSUE TITLE
习题4.2中多项式分布前面漏了一项？

### ISSUE THREAD

**Issue by yuioqp** [datawhalechina/statistical-learning-method-solutions-manual#34]
证明公式(4.11)处第二步：
![image](https://user-images.githubusercontent.com/88842228/219592039-a3618031-7610-442f-9fd1-77b0a5e12941.png)
而多项分布的概率公式应该是这样的：
![image](https://user-images.githubusercontent.com/88842228/219592138-608ad39f-c537-4b2a-81a7-eb56cdc1b25a.png)
虽然这样不影响最后结果。

**Comment by Relph1119** [comment]
解题中使用的是PRML书中的Dirichlet分布的公式，并不是多项分布的传统公式，虽然基本上是一致的
