### ISSUE TITLE
习题8.1中计算总分类其的误差率有对应的公式支撑吗？

### ISSUE THREAD

**Issue by hgospodar** [datawhalechina/statistical-learning-method-solutions-manual#38]
习题8.1中 class MyAdaBoost 中的fit函数，计算总分类器的误差有点看不懂，能帮助解释一下吗？如下图所示
![Snipaste_2023-05-19_18-30-44](https://github.com/datawhalechina/statistical-learning-method-solutions-manual/assets/108121179/84fbf95b-ac94-4fb8-bcba-98df3190433f)

**Comment by Relph1119** [comment]
这里使用的是MAE计算误差，多除了2，谢谢指正
