### ISSUE TITLE
某些答案中的页码给定错误

### ISSUE THREAD

**Issue by yzmyyff** [datawhalechina/statistical-learning-method-solutions-manual#40]
习题21.3中, 
```
根据书中第422页PageRank的一般定义
```

我使用的是<机器学习方法>这一本书, 实际的页码应该是355.
我们的项目现在应该是<机器学习方法>的答案而不是<统计学习方法>, 因为<统计学习方法>没有第三篇深度学习的内容.

**Comment by Relph1119** [comment]
谢谢反馈，后期我们将删除所有页面，只标明章节号
