### ISSUE TITLE
习题8.1的解答中，第3步：自编程实现AdaBoost算法代码有误。

### ISSUE THREAD

**Issue by LiShuang-codes** [datawhalechina/statistical-learning-method-solutions-manual#42]
在fit()方法中，传入update_w()方法的参数y_predict，根据李航书，应该是基本分类器Gm的分类值，也就是代码中的参数sign，而不是总分类器G的分类值y_predict。在将代码修改后，经过6轮迭代，模型收敛，而不是8轮。

**Comment by Relph1119** [comment]
谢谢反馈，已修改，目前迭代次数为5次
